"""More renaming, Win name to category

Revision ID: 39e50a8aa699
Revises: 42fdd8e5d468
Create Date: 2025-02-26 09:40:47.682029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e50a8aa699'
down_revision: Union[str, None] = '42fdd8e5d468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('wins', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wins', 'category')
    # ### end Alembic commands ###
