"""Added created_at to wins

Revision ID: 3d2bc8f326b2
Revises: 39e50a8aa699
Create Date: 2025-03-03 08:34:24.544635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2bc8f326b2'
down_revision: Union[str, None] = '39e50a8aa699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wins', 'created_at')
    # ### end Alembic commands ###
