"""Renamed a few table names for simplicity sake.

Revision ID: 42fdd8e5d468
Revises: 608106e17e1d
Create Date: 2025-02-26 08:06:23.123452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fdd8e5d468'
down_revision: Union[str, None] = '608106e17e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_categories', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('custom_categories', 'category_name')
    op.add_column('predefined_categories', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('predefined_categories', 'category_name')
    op.add_column('wins', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('wins', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wins', 'name')
    op.add_column('predefined_categories', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('predefined_categories', 'name')
    op.add_column('custom_categories', sa.Column('category_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('custom_categories', 'name')
    # ### end Alembic commands ###
