"""category_type unncessary

Revision ID: 501b769cd52c
Revises: c8ed3fdd4368
Create Date: 2025-02-26 06:29:54.580400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501b769cd52c'
down_revision: Union[str, None] = 'c8ed3fdd4368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wins', 'category_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
