"""category_id is unncessary

Revision ID: 608106e17e1d
Revises: 501b769cd52c
Create Date: 2025-02-26 06:31:09.092775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608106e17e1d'
down_revision: Union[str, None] = '501b769cd52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wins', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
