"""custom_categories, dev_wins and wins tables refactored to be clearer in naming scheme and added necessary relationships between them.

Revision ID: 619bfe5814e3
Revises: 9ab56d03d2c8
Create Date: 2025-02-25 06:52:25.793214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619bfe5814e3'
down_revision: Union[str, None] = '9ab56d03d2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_categories', sa.Column('category_name', sa.String(length=50), nullable=False))
    op.add_column('custom_categories', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('custom_categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('custom_categories', 'name')
    op.add_column('dev_wins', sa.Column('category_name', sa.String(), nullable=False))
    op.drop_constraint('dev_wins_user_id_fkey', 'dev_wins', type_='foreignkey')
    op.drop_column('dev_wins', 'title')
    op.drop_column('dev_wins', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dev_wins', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dev_wins', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('dev_wins_user_id_fkey', 'dev_wins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dev_wins', 'category_name')
    op.add_column('custom_categories', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('custom_categories', 'created_at')
    op.drop_column('custom_categories', 'description')
    op.drop_column('custom_categories', 'category_name')
    # ### end Alembic commands ###
