"""Renamed DevWin to PredefinedCategory

Revision ID: 870df2cd3e46
Revises: 660bfb2418e3
Create Date: 2025-02-25 08:49:12.370418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870df2cd3e46'
down_revision: Union[str, None] = '660bfb2418e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
