"""Added new logic for Wins class, supports both predefined and custom categories

Revision ID: 9ab56d03d2c8
Revises: a802460a8901
Create Date: 2025-02-25 06:06:59.709158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab56d03d2c8'
down_revision: Union[str, None] = 'a802460a8901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('wins', sa.Column('category_type', sa.String(), nullable=False))
    op.drop_constraint('wins_custom_category_id_fkey', 'wins', type_='foreignkey')
    op.drop_column('wins', 'category')
    op.drop_column('wins', 'custom_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('custom_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('wins', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('wins_custom_category_id_fkey', 'wins', 'custom_categories', ['custom_category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wins', 'category_type')
    op.drop_column('wins', 'category_id')
    # ### end Alembic commands ###
