"""Permission nullable=False

Revision ID: a802460a8901
Revises: c98ce9222e99
Create Date: 2025-02-25 01:23:19.163180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a802460a8901'
down_revision: Union[str, None] = 'c98ce9222e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permission_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permission_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
