"""Added missing category_name column to wins table

Revision ID: abd1aa7a0538
Revises: 619bfe5814e3
Create Date: 2025-02-25 08:30:30.529007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd1aa7a0538'
down_revision: Union[str, None] = '619bfe5814e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('category_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wins', 'category_name')
    # ### end Alembic commands ###
