"""Removed unnecessary relationship between Win and CustomCategory. All relationships will be handled by the user.id

Revision ID: c8ed3fdd4368
Revises: 45acba61a637
Create Date: 2025-02-26 06:26:54.293374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ed3fdd4368'
down_revision: Union[str, None] = '45acba61a637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
