"""Added permission_level to users

Revision ID: c98ce9222e99
Revises: 09614c27b668
Create Date: 2025-02-25 01:22:31.975608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98ce9222e99'
down_revision: Union[str, None] = '09614c27b668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission_level')
    # ### end Alembic commands ###
