"""Added title to Wins, added title to several schemas.

Revision ID: eeffb74f1c1d
Revises: 3d2bc8f326b2
Create Date: 2025-03-04 08:10:02.579205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeffb74f1c1d'
down_revision: Union[str, None] = '3d2bc8f326b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wins', sa.Column('title', sa.String(), server_default='Old_Data', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wins', 'title')
    # ### end Alembic commands ###
